#!/usr/bin/env python3
"""06_export_embeddings.py — Export trained model embeddings + pgvector SQL.

Generates deployment artifacts:
  1. Load the best model checkpoint from model/checkpoints/best_model.pt
  2. Load and preprocess features from data/processed/ma_ab_features.csv
  3. Run all bands through the model to get 16-dim L2-normalized embeddings
  4. Join with band names from data/raw/metal_bands.csv
  5. Output: data/processed/deployment_embeddings.csv
  6. Output: data/processed/load_embeddings.sql (pgvector-ready)

The SQL file is loaded directly into Metaloreian's PostgreSQL (pgvector).
No separate serving layer — the Go backend queries pgvector directly.

Usage:
    python pipeline/06_export_embeddings.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_DIR = Path(__file__).resolve().parent.parent
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from model.tower import BandEncoder
from model.dataset import preprocess_features

DATA_DIR = PROJECT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

FEATURES_CSV = PROCESSED_DIR / "ma_ab_features.csv"
METAL_BANDS_CSV = RAW_DIR / "metal_bands.csv"
BEST_MODEL_PATH = PROJECT_DIR / "model" / "checkpoints" / "best_model.pt"

DEPLOYMENT_CSV = PROCESSED_DIR / "deployment_embeddings.csv"
SQL_OUTPUT = PROCESSED_DIR / "load_embeddings.sql"


# ---------------------------------------------------------------------------
# Embedding computation
# ---------------------------------------------------------------------------

@torch.no_grad()
def compute_all_embeddings(
    model: BandEncoder,
    feature_matrix: np.ndarray,
    device: torch.device,
    batch_size: int = 1024,
) -> np.ndarray:
    """Run all bands through the model and return L2-normalized embeddings."""
    model.eval()
    features_t = torch.from_numpy(feature_matrix).float()
    embeddings = []

    for start in range(0, len(features_t), batch_size):
        batch = features_t[start : start + batch_size].to(device)
        emb = model(batch).cpu().numpy()
        embeddings.append(emb)

    return np.vstack(embeddings)


def escape_sql_string(s: str) -> str:
    """Escape a value for use in a SQL string literal."""
    if pd.isna(s):
        return "Unknown"
    return str(s).replace("\x00", "").replace("\\", "\\\\").replace("'", "''")


def generate_sql(
    band_ids: np.ndarray,
    band_names: pd.Series,
    embeddings: np.ndarray,
    output_path: Path,
) -> None:
    """Generate a pgvector-ready SQL file for loading embeddings.

    The SQL is idempotent: uses INSERT ... ON CONFLICT DO UPDATE.
    """
    embed_dim = embeddings.shape[1]

    lines = []
    lines.append("-- Auto-generated by pipeline/06_export_embeddings.py")
    lines.append("-- Load band embeddings into pgvector\n")
    lines.append("CREATE EXTENSION IF NOT EXISTS vector;\n")
    lines.append(f"""CREATE TABLE IF NOT EXISTS band_embeddings (
    band_id BIGINT PRIMARY KEY,
    band_name TEXT,
    embedding vector({embed_dim})
);\n""")

    lines.append("-- Upsert all embeddings")
    lines.append("BEGIN;\n")

    for i, (band_id, name) in enumerate(zip(band_ids, band_names)):
        vec_str = ",".join(f"{v:.8f}" for v in embeddings[i])
        safe_name = escape_sql_string(name)
        lines.append(
            f"INSERT INTO band_embeddings (band_id, band_name, embedding) "
            f"VALUES ({int(band_id)}, '{safe_name}', '[{vec_str}]') "
            f"ON CONFLICT (band_id) DO UPDATE SET "
            f"band_name = EXCLUDED.band_name, embedding = EXCLUDED.embedding;"
        )

    lines.append("\nCOMMIT;\n")

    # IVFFlat index for ANN search
    lines.append("-- Create IVFFlat index for approximate nearest neighbor search")
    lines.append(
        "CREATE INDEX IF NOT EXISTS band_embeddings_idx "
        "ON band_embeddings USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100);\n"
    )

    lines.append(f"-- Total bands: {len(band_ids)}")

    output_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 70)
    print("heavyML Pipeline Step 06: Export Embeddings")
    print("=" * 70)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")

    # ------------------------------------------------------------------
    # 1. Load checkpoint
    # ------------------------------------------------------------------
    print("\n--- Loading model checkpoint ---")
    if not BEST_MODEL_PATH.exists():
        print(f"ERROR: Checkpoint not found: {BEST_MODEL_PATH}")
        print("Run model training first: python -m model.train")
        sys.exit(1)

    checkpoint = torch.load(BEST_MODEL_PATH, map_location=device, weights_only=True)
    input_dim = checkpoint["input_dim"]
    hidden_dim = checkpoint["hidden_dim"]
    embed_dim = checkpoint["embed_dim"]
    dropout = checkpoint["dropout"]
    n_audio_dims = checkpoint.get("n_audio_dims", input_dim)  # fallback for v1 models
    feature_names = checkpoint.get("feature_names", [])

    print(f"  Architecture: {input_dim} -> {hidden_dim} -> {embed_dim} (audio={n_audio_dims})")
    print(f"  Trained epoch: {checkpoint.get('epoch', '?')}")
    print(f"  Val loss: {checkpoint.get('val_loss', '?')}")
    if feature_names:
        print(f"  Features ({len(feature_names)}): {', '.join(feature_names)}")

    # ------------------------------------------------------------------
    # 2. Rebuild model and load weights
    # ------------------------------------------------------------------
    model = BandEncoder(
        input_dim=input_dim,
        hidden_dim=hidden_dim,
        embed_dim=embed_dim,
        dropout=dropout,
        n_audio_dims=n_audio_dims,
    ).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    print("  Model loaded successfully.")

    # ------------------------------------------------------------------
    # 3. Load and preprocess features
    # ------------------------------------------------------------------
    print("\n--- Loading features ---")
    if not FEATURES_CSV.exists():
        print(f"ERROR: Feature file not found: {FEATURES_CSV}")
        sys.exit(1)

    band_ids, feature_matrix, current_feature_names = preprocess_features(FEATURES_CSV, METAL_BANDS_CSV)
    n_bands, actual_input_dim = feature_matrix.shape
    print(f"  Bands: {n_bands:,}")
    print(f"  Feature dims: {actual_input_dim}")

    if actual_input_dim != input_dim:
        print(
            f"  WARNING: Feature dim mismatch! Model expects {input_dim}, "
            f"got {actual_input_dim}. This will cause an error."
        )
        sys.exit(1)

    # ------------------------------------------------------------------
    # 4. Compute embeddings
    # ------------------------------------------------------------------
    print("\n--- Computing embeddings ---")
    embeddings = compute_all_embeddings(model, feature_matrix, device)
    print(f"  Embedding shape: {embeddings.shape}")

    # Verify L2 normalization
    norms = np.linalg.norm(embeddings, axis=1)
    print(f"  L2 norm range: [{norms.min():.6f}, {norms.max():.6f}] (should be ~1.0)")

    # ------------------------------------------------------------------
    # 5. Join with band names
    # ------------------------------------------------------------------
    # Use names from the features CSV (which has de-duplicated names from
    # the linkage step) rather than metal_bands.csv (which has duplicate
    # Band IDs that cause wrong name lookups).
    print("\n--- Joining band names ---")
    features_df = pd.read_csv(FEATURES_CSV, usecols=["ma_band_id", "ma_name"])
    name_map = dict(zip(features_df["ma_band_id"], features_df["ma_name"]))
    band_names = pd.Series([name_map.get(int(bid), "Unknown") for bid in band_ids])
    n_named = (band_names != "Unknown").sum()
    print(f"  Matched {n_named:,}/{n_bands:,} band names")

    # ------------------------------------------------------------------
    # 6. Save deployment CSV
    # ------------------------------------------------------------------
    print("\n--- Saving deployment embeddings ---")
    emb_cols = [f"emb_{i}" for i in range(embed_dim)]
    deploy_df = pd.DataFrame(embeddings, columns=emb_cols)
    deploy_df.insert(0, "band_id", band_ids)
    deploy_df.insert(1, "band_name", band_names.values)
    deploy_df.to_csv(DEPLOYMENT_CSV, index=False)
    print(f"  Saved: {DEPLOYMENT_CSV}")
    print(f"  Shape: {deploy_df.shape}")

    # ------------------------------------------------------------------
    # 7. Generate SQL load file
    # ------------------------------------------------------------------
    print("\n--- Generating SQL load file ---")
    generate_sql(band_ids, band_names, embeddings, SQL_OUTPUT)
    print(f"  Saved: {SQL_OUTPUT}")
    sql_size_mb = SQL_OUTPUT.stat().st_size / (1024 * 1024)
    print(f"  Size: {sql_size_mb:.1f} MB")

    # ------------------------------------------------------------------
    # Done
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("DONE — Deployment artifacts ready:")
    print(f"  Embeddings CSV: {DEPLOYMENT_CSV}")
    print(f"  SQL load file:  {SQL_OUTPUT}")
    print(f"  Bands: {n_bands:,} | Embed dim: {embed_dim}")
    print()
    print("Next: load into Metaloreian's PostgreSQL:")
    print(f"  psql $DATABASE_URL < {SQL_OUTPUT}")
    print("=" * 70)


if __name__ == "__main__":
    main()
